DELIMITER //
CREATE FUNCTION TO_CHAR(date DATE, format VARCHAR(20))
RETURNS VARCHAR(20)
BEGIN
  DECLARE result VARCHAR(20);
  SET result = DATE_FORMAT(date, format);
  RETURN result;
END//
DELIMITER ;
